Fix two bugs in the printing of float vectors.
The first bug is a casting error due to a missing declaration of
CVfloatvec2String in icm_icm2c.c:

codegen/icm_icm2c.c: In function 'GetNextAny':
codegen/icm_icm2c.c:758:7: warning: implicit declaration of function
'CVfloatvec2String'
codegen/icm_icm2c.c:758:14: warning: assignment makes pointer from
integer without a cast

Due to the missing declaration, the return type defaults to int. On
platforms where sizeof(void*)>sizeof(int), this discards the high order
bits and the pointer becomes invalid.

After adding the missing declaration another error is detected by
the compiler:

codegen/icm_icm2c.c: In function 'GetNextAny':
codegen/icm_icm2c.c:758:7: error: incompatible type for argument 1 of
'CVfloatvec2String'
print/convert.h:7:14: note: expected 'floatvec' but argument is of type
'float'